### ISSUE TITLE
Aktualności.

### ISSUE THREAD

**Issue by fanooel** [openpkw/openpkw#10]
## Komunikat Lidera Zespołu Analitycznego

W związku z charakterem projektowanego systemu zdecydowałem się odrzucić popularne dziś metodyki zwinne i ekstremalne w projekcie. Zarówno cel jak i charakter produktu końcowego przemawiają za zastosowaniem modelu kaskadowego lub prototypowego. Zespół Analizy obecnie rozważa kilka możliwych wariantów budowy systemu. Efekty pracy będą znane w ciągu najbliższego tygodnia.

## Komunikat Lidera Zespołu Architektury

Zespół analityki omawia z zespołem architektury pierwsze propozycje architektury systemu i możliwości zastosowania obecnych już na rynku protokołów komunikacyjnych.

## Komunikat Lidera Zespołu Prawnego

Zostały zdiagnozowane trzy obszary związane z uruchomieniem projektu: (1) decyzja odnośnie licencji i modelu otwarcia projektu, (2) audyt wymagań prawnych i wynikających z nich aspektów technicznych, (3) pozyskanie informacji o obecnym systemie z PKW i współpraca z PKW. W dniu dzisiejszym została podjęta finalna decyzja o udostępnieniu projektu na licencji AGPL oraz ustalono zasady współpracy deweloperów. W najbliższym tygodniu zostanie podjęta próba pozyskania danych i informacji z PKW oraz zaproszenie PKW do współpracy. Jednocześnie nawiązono kontakt z podobną inicjatywą w USA (California Association of Voting Officials), czego konsekwencją będą wspólne prace nad głównymi elementami systemów głosowań, które są tożsame niezależnie od miejsca wykorzystania.

## Komunikat Lidera Zespołu Public Relations

Uzyskaliśmy zainteresowanie mediów głównego nurtu, w tym Polskiego Radia program Trzeci, telewizji Polsat oraz Polsat News. Liczba osób, które biorą udział w projekcie urosła do 600 osób, w tym prawników, programistów i testerów użyteczności systemu. Wzbudziliśmy zainteresowanie w mediach społecznościowych – ponad 3400 polubień na Facebooku, ponad 200 obserwujących na Twitterze, 100 zainteresowanych w Google+, w Internecie zaś toczy się burzliwa dyskusja na temat projektu. Inicjatywa ma pozytywny oddźwięk wśród osób, które o niej słyszały. Do popierających ideę włączyły się w ostatnim tygodniu: Fundacja Nowoczesna Polska, Fundacja ePaństwo i projekt Koduj dla Polski, Polsko-Amerykańska Fundacja Edukacji i Rozwoju Ekonomicznego (PAFERE), Fundacja Promocji Retroinformatyki „Dawne Komputery i Gry”, OpenData, Niebezpiecznik.pl, Fundacja Media 3.0 oraz Centralny Instytut Analiz Polityczno-Prawnych.

### Komunikat Lidera Zespołu Technicznego

W ostatnim czasie wdrożyliśmy szyfrowanie SSL dla całego serwisu OpenPKW. Z racji dużego ruchu na stronie uruchomiliśmy usługę CDN za pomocą CloudFlare. Pojawiły się nowe listy dyskusyjne. Współpracujemy też z grafikami, którzy przygotują nowy design serwisu. Nawiązaliśmy również współpracę z firmami, które zajmą się testami bezpieczeństwa webaplikacji.

**Comment by adamkowalewski** [comment]
zamykam jurassic ticket
