### ISSUE TITLE
Czy to wszystkie dokumenty od PKW?

### ISSUE THREAD

**Issue by KeineSorgen** [openpkw/openpkw#11]
Wczoraj był commit kilku dokumentów od PKW. Czy to wszystkie dokumenty, które PKW udostępni, czy należy się spodziewać kolejnych paczek?

Czy PKW udostępni kod źródłowy ostatnio użytego systemu PKW 2.0?

Czy zespół analityczny dysponuje czymś ponadto? Czy analiza prawna pozwoliła na stworzenie dokumentów analitycznych?

**Comment by dedik** [comment]
Powinno być 6 załączników jak na razie w repo są 3 więc raczej brakuje jeszcze kilku dokumentów :>

**Comment by fanooel** [comment]
Następny komit da pewnie Rafał Malujda.
