### ISSUE TITLE
Poszukiwani analitycy.

### ISSUE THREAD

**Issue by fanooel** [openpkw/openpkw#13]
Witam,

Jeżeli jest ktoś kto chciałby dołączyć do nowego zespołu analtyków, to proszę dać znać na maila: tomlee@szluug.org

Zespół jest tworzony od niemal zera. Są już tam pierwsze osoby. Praca ma być oparta na OpenProject i wspólnej pracy na dokumentach.

Zespół analityków to Ci co maja przygotować dokumentację i wymagania dla prgramistów. Tak gwoli uściślenia.

**Comment by krzysztofantczak** [comment]
Jak bardzo bogate doświadczenie w tworzeniu dokumentacji analitycznej należy posiadać, by podjąć się tego zadania?

**Comment by fanooel** [comment]
Jeżeli brak doświadczenia jest nadrabiany chęciami nauczenia się czegoś, smykałką albo doświadczeniem jak dokumentacji nie robić, to można się zgłaszać. Chętnie podziałamy.

**Comment by adamkowalewski** [comment]
zamykam jurassic ticket
