### ISSUE TITLE
Ogłoszenie.

### ISSUE THREAD

**Issue by fanooel** [openpkw/openpkw#9]
Witam,

W celu uporządkowania dyskusji proszę o zapisanie się i przeniesienie dyskusji na jedną z poniższych list: 
http://openpkw.pl/mailman/listinfo

Docelowo HitHub będzie miejscem na dyskusje o kodzie. Wszystkie uznane dokumenty będą dołączane do repozytorium i uzupełnię na bieżąco wiki.

Uprzedzając dyskusję, dlaczego listy:
  * Mamy ponad 200 ludzi na nich zapisanych
  * Możliwość głębokiego wątkowania
  * Docierane informacji bez potrzeby logowania
  * Bo to podstawowy kanał wymiany informacji i dyskusji w OpenSource.

Za jakiś czas wyczyszczę bieżące "issue".

Bardzo dziękuję za zainteresowanie i wsparcie- zapraszam serdecznie do projektu, dyskusji i mam nadzieję jak najszybszego kodowania i testowania.

**Comment by adamkowalewski** [comment]
zamykam jurassic ticket
